#!/bin/bash

yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 111; }
try() { "$@" || die "cannot $*"; }

nft -j list ruleset | \
json_pp | \
jq '.[]|.[]|.[]| select(.name=="blocklist_dyn")|.elem' | \
grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' > \
/etc/nftables.blocklist.tmp

cat /etc/nftables.blocklist >> /etc/nftables.blocklist.tmp

/usr/bin/iprange /etc/nftables.blockcidrs /etc/nftables.blocklist.tmp > /etc/nftables.blocklist

rm -f /etc/nftables.blocklist.tmp

true
